Core2Walkthrough/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

/*
 *  About: Static page.  Nothing fancy, just showing HTMl.
 */
namespace Core2Walkthrough.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Core2Walkthrough/Pages/Activity.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Threading.Tasks;
using Core2Walkthrough.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

/*
 *  About: Moderately complex page that: 
 *  -- gets enabled activities, 
 *  -- allows a user to activate an activity, 
 *  -- prevents user from clicking on the activity until the time is up
 *  -- increments user's XP.
 *  
 *  Make use of:
 *  -- complex DB queries
 *  -- Entity Framework updates
 *  -- Entity Framework deletes
 *  -- HttpContext.Session
 */
namespace Core2Walkthrough.Pages
{
    public class ActivityModel : PageModel
    {
        private readonly AppDbContext _db;

        [TempData]
        public string Message { get; set; }// no private set b/c we need data backl

        // no accessor as this just shows the information recieved before rendering the page.
        public IList<ACTIVITY> ActivityList { get; private set; }

        //Constructor
        public ActivityModel(AppDbContext db)
        {
            //Get the database context so we can move data to and from the tables.
            _db = db;
        }

        //When the page is being fetched, load some data to be rendered.
        public async Task OnGetAsync()
        {
            int userID = 0;
            int.TryParse(HttpContext.Session.GetString("id"), out userID);

            var con = _db.Database.GetDbConnection();
            try
            {
                await con.OpenAsync();
                using (var command = con.CreateCommand())
                {
                    string q = @" SELECT a.ID,
		                        a.TITLE,
		                        a.DESCRIPTION,
		                        a.XP,
		                        a.COOL_OFF_MINUTES,
		                        a.IS_ACTIVE,
		                        a.DATE_ENTERED
                         , IIF(DATEDIFF(SECOND, b.DATE_ENTERED, GETDATE()) < a.cool_off_minutes * 60, a.cool_off_minutes * 60 - DATEDIFF(SECOND, b.DATE_ENTERED, GETDATE()), 0) as TIME_LEFT
                         FROM ACTIVITY a  WITH(NOLOCK)
                         LEFT JOIN ACTIVITY_LOG b  WITH(NOLOCK) on a.ID = b.ID_ACTIVITY
                         WHERE b.ID_USER = @userid 
                            AND a.IS_ACTIVE = 1

                        UNION

                        SELECT a.ID,
	                        a.TITLE,
	                        a.DESCRIPTION,
	                        a.XP,
	                        a.COOL_OFF_MINUTES,
	                        a.IS_ACTIVE,
	                        a.DATE_ENTERED
	                        , 0 as TIME_LEFT
                        FROM ACTIVITY a WITH(NOLOCK)
                        WHERE a.IS_ACTIVE = 1 
                        and a.ID not in (select z.ID
	                        FROM ACTIVITY z WITH(NOLOCK)
	                        LEFT JOIN ACTIVITY_LOG b  WITH(NOLOCK) on a.ID = b.ID_ACTIVITY
	                        WHERE b.ID_USER = @userid )";
                    command.CommandText = q;

                    DbParameter tempParameter = command.CreateParameter();
                    tempParameter.ParameterName = "@userid";
                    tempParameter.Value = userID;
                    command.Parameters.Add(tempParameter);

                    System.Data.Common.DbDataReader reader = await command.ExecuteReaderAsync();

                    if (reader.HasRows)
                    {
                        ActivityList = new List<ACTIVITY>();

                        while (await reader.ReadAsync())
                        {
                            var row = new ACTIVITY
                            {
                                ID = reader.GetInt32(0),
                                Title = reader.GetString(1),
                                Description = reader.GetString(2),
                                XP = reader.GetInt32(3),
                                COOL_OFF_MINUTES = reader.GetInt32(4),
                                IS_ACTIVE = reader.GetBoolean(5),
                                DATE_ENTERED = reader.GetDateTime(6),
                                TIME_LEFT = reader.GetInt32(7)
                            };
                            ActivityList.Add(row);
                        }
                    }
                    reader.Dispose();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
            finally
            {
                con.Dispose();
            }
        }

        //The user signals there is an action to do.  Notice how the words between "OnPost" and "Async" match up with the CHTML's "asp-page-handler"
        // the 'id' is from "asp-route-" on the CHTML.  Could have used asp-route-foo, but the parameter would need to be changed to 'int foo'.
        public async Task<IActionResult> OnPostActivityDoAsync(int id)
        {
            int userID = 0;

            if (HttpContext.Session.GetString("id") != null)
            {
                int.TryParse(HttpContext.Session.GetString("id"), out userID);

                // 1.  Update XP on user profile
                ACTIVITY tempActivity = await _db.ACTIVITY_DBSet.FindAsync(id);
                USERS tempUser = await _db.USER_DBSet.FindAsync(userID);

                tempUser.XP += tempActivity.XP;
                _db.USER_DBSet.Update(tempUser);
                _db.SaveChanges();


                // 2.  Upate log.
                ACTIVITY_LOG temp = new ACTIVITY_LOG();

                // If you got this far then the button is enabled so remove all instances of the old.
                var temp2 = _db.ACTIVITY_LOG_DBSet.Where(s => s.ID_ACTIVITY == id && s.ID_USER == userID);
                _db.ACTIVITY_LOG_DBSet.RemoveRange(temp2);
                _db.SaveChanges();

                temp.ID_ACTIVITY = id;

                temp.ID_USER = userID;
                temp.DATE_ENTERED = DateTime.Now;

                _db.ACTIVITY_LOG_DBSet.Add(temp);
                await _db.SaveChangesAsync();
            }

            Message = $"Activity started; XP added.";

            return RedirectToPage("/Activity");
        }
    }
}

Core2Walkthrough/Pages/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Core2Walkthrough.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

/*
 *  About: Moderately complex page that: 
 *  -- adds activities, 
 *  -- disable/enable activities
 *  -- remove news
 *  -- add news
 *  -- remove users
 *  
 *  Make use of:
 *  -- Entity Framework updates
 *  -- Entity Framework deletes
 *  -- Entity Framework create
 *  -- HttpContext.Session
 */
namespace Core2Walkthrough.Pages
{
    public class AdminModel : PageModel
    {
        private readonly AppDbContext _db; // access route to and from the DB.

        [TempData]
        public string Message { get; set; }// no private set b/c we need data back

        [BindProperty] // survive the journey _BACK_ from the user.
        public NEWS NewsAdd { get; set; }// private not set because the data is needed back

        public IList<NEWS> NewsList { get; private set; }// private set so don't need to have data back.. just to show.

        public IList<USERS> UserList { get; private set; }// private set so don't need to have data back.. just to show.

        public IList<ACTIVITY> ActivityList { get; private set; }// private set so don't need to have data back.. just to show.

        [BindProperty]// survive the journey _BACK_ from the user.
        public ACTIVITY ActivityAdd { get; set; }

        //Constructor
        public AdminModel(AppDbContext db)
        {
            //Get the database context so we can move data to and from the tables.
            _db = db;
        }

        //When the page is being fetched, load some data to be rendered.
        public async Task OnGetAsync()
        {

            NewsList = await _db.NEWS_DBSet.AsNoTracking().ToListAsync();
            UserList = await _db.USER_DBSet.AsNoTracking().ToListAsync();
            ActivityList = await _db.ACTIVITY_DBSet.AsNoTracking().ToListAsync();
        }

        //The user signals there is an action to do.  Notice how the words between "OnPost" and "Async" match up with the CHTML's "asp-page-handler"
        public async Task<IActionResult> OnPostNewsAddAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //Snag the current date time.
            NewsAdd.DATE_ENTERED = DateTime.Now;
            
            //Add it to the News database set.
            _db.NEWS_DBSet.Add(NewsAdd);
            
            //Update it.
            await _db.SaveChangesAsync();

            //Inform the user of much success.
            Message = $"News added!";

            //Send it back to the admin page.
            return RedirectToPage("/Admin");
        }

        //The user signals there is an action to do.  Notice how the words between "OnPost" and "Async" match up with the CHTML's "asp-page-handler"
        public async Task<IActionResult> OnPostActivityAddAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ActivityAdd.DATE_ENTERED = DateTime.Now;
            _db.ACTIVITY_DBSet.Add(ActivityAdd);
            await _db.SaveChangesAsync();

            Message = $"Activity added!";

            return RedirectToPage("/Admin");
        }

        //The user signals there is an action to do.  Notice how the words between "OnPost" and "Async" match up with the CHTML's "asp-page-handler"
        // the 'id' is from "asp-route-" on the CHTML.  Could have used asp-route-foo, but the parameter would need to be changed to 'int foo'.
        public async Task<IActionResult> OnPostActivityDisableAsync(int id)
        {
            //Find the data row first, before editing can happen.
            var temp = await _db.ACTIVITY_DBSet.FindAsync(id);

            if (temp != null)
            {
                temp.IS_ACTIVE = !temp.IS_ACTIVE;

                //make sure the database context knows there is something to update.
                _db.Attach(temp).State = EntityState.Modified;

                //Have it run the update.
                _db.ACTIVITY_DBSet.Update(temp);
                await _db.SaveChangesAsync();

            }

            Message = $"Activity updated";

            return RedirectToPage("/Admin");
        }

        //The user signals there is an action to do.  Notice how the words between "OnPost" and "Async" match up with the CHTML's "asp-page-handler"
        // the 'id' is from "asp-route-" on the CHTML.  Could have used asp-route-foo, but the parameter would need to be changed to 'int foo'.
        public async Task<IActionResult> OnPostDeleteNewsAsync(int id)
        {
            var temp = await _db.NEWS_DBSet.FindAsync(id);

            if (temp != null)
            {
                _db.NEWS_DBSet.Remove(temp);
                await _db.SaveChangesAsync();

            }

            Message = $"News deleted.";


            return RedirectToPage();
        }

        //The user signals there is an action to do.  Notice how the words between "OnPost" and "Async" match up with the CHTML's "asp-page-handler"
        // the 'id' is from "asp-route-" on the CHTML.  Could have used asp-route-foo, but the parameter would need to be changed to 'int foo'.
        public async Task<IActionResult> OnPostDeleteUserAsync(int id)
        {
            //Find the record to remove.
            var temp = await _db.USER_DBSet.FindAsync(id);

            if (temp != null)
            {
                //Tell the DB context to remove it.
                _db.USER_DBSet.Remove(temp);
                //Save it.
                await _db.SaveChangesAsync();
            }

            Message = $"User deleted.";

            return RedirectToPage();
        }
    }
}

Core2Walkthrough/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Core2Walkthrough.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Core2Walkthrough/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Core2Walkthrough.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

/*
 *  About: Starting landing page when a user would visit the site.
 *  2017.12.30 - created
 *  -- display any news
 *  -- display static text.
 *  -- house the log out button.
 *  
 *  Make use of:
 *  -- basic DB binding
 *  -- Entity Framework retrieves
 *  -- HttpContext.Session
 */
namespace Core2Walkthrough.Pages
{
    /*
     * http://www.entityframeworktutorial.net/stored-procedure-in-entity-framework.aspx
     * http://www.entityframeworktutorial.net/Querying-with-EDM.aspx
     * */



    public class IndexModel : PageModel
    {
        private readonly AppDbContext _db;

        public IList<NEWS> NewsList { get; private set; }// private set so don't need to have data back.. just to show.

        [TempData]
        public string Message { get; set; }// no private set b/c we need data back



        //Constructor
        public IndexModel(AppDbContext db)
        {
            //Get the database context so we can move data to and from the tables.
            _db = db;
        }

        //When the page is being fetched, load some data to be rendered.
        public async Task OnGetAsync()
        {
            NewsList = await _db.NEWS_DBSet.AsNoTracking().ToListAsync();
        }

        public IActionResult OnPostLogOut()
        {
            HttpContext.Session.Clear();
            Message = "Logged out";

            return RedirectToPage();
        }



    }
}

Core2Walkthrough/Pages/Test.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

/*
 *  About: Basic page showing setup for other various controls that did not fit in the original tutorials
 *  -- drop down lists
 */
namespace Core2Walkthrough.Pages
{

    public class TestModel : PageModel
    {
        [TempData]
        public string Message { get; set; }// no private set b/c we need data back


        public IEnumerable<SelectListItem> testDD { get; set; }// DropDown Testing

        [BindProperty]
        public string testDDSelected { get; set; }//DropDown Testing.. gets the selected value on post

        [BindProperty]
        public string testRadioButtonSelected { get; set; }//Radiobutton Testing.. gets the selected value on post

        [BindProperty]
        public bool isChecked { get; set; }//Checkbox Testing.. gets the selected value on post


        public IEnumerable<SelectListItem> testDDAJAX { get; set; }// DropDown Testing

        [BindProperty]
        public string testDDSelectedAJAX { get; set; }//DropDown Testing.. gets the selected value on post

        public TestModel(AppDbContext db)
        {
            //DropDown Testing - fill values for hte list.
            IList<string> foo = new List<string>();
            foo.Add("aa");
            foo.Add("bb");
            foo.Add("cc");

            //convert that to a 'select list item'.
            testDD = from a in foo
                     select new SelectListItem
                     {
                         Text = a,
                         Value = a
                     };

            foo = new List<string>();
            foo.Add("a1");
            foo.Add("b1");
            foo.Add("c1");

            //convert that to a 'select list item'.
            testDDAJAX = from a in foo
                     select new SelectListItem
                     {
                         Text = a,
                         Value = a
                     };
        }

        //DropDown Testing - display selected item to show it was picked.
        public IActionResult OnPostDropDownList()
        {
            Message = "Dropdown: " + testDDSelected;
            return RedirectToPage();
        }

        //RadioButton Testing - display selected item to show it was picked.
        public IActionResult OnPostRadioButton()
        {
            Message = "Radiobutton: " + testRadioButtonSelected.ToString();
            return RedirectToPage();
        }

        //Checkbox Testing - display selected item to show it was picked.
        public IActionResult OnPostCheckBox()
        {
            Message = "Checkbox: " + isChecked.ToString();
            return RedirectToPage();
        }


        //Selected change event triggers ajax call to get data from the post and return it modfified.
        public ContentResult OnGetList(string derp)
        {
            return Content("nuts -- " + derp);
        }

    }
}

Core2Walkthrough/Pages/About.cshtml
@page
@model Core2Walkthrough.Pages.AboutModel
@{
    ViewData["Title"] = "About";
}

<h2>About</h2>
<p>Static 'About Page'.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fringilla erat quis odio vehicula ultrices. Mauris id lorem neque. Phasellus id accumsan metus. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas at justo vel ligula auctor elementum sit amet feugiat nibh. Duis euismod et nulla ac efficitur. Vivamus ac sapien aliquet, malesuada ligula euismod, dapibus leo. Maecenas non dictum augue, vitae convallis neque. Aliquam venenatis nisl quis tristique accumsan. In consectetur eleifend arcu feugiat vulputate. Suspendisse nec venenatis velit. Vivamus non justo leo. Nam purus neque, feugiat et feugiat ut, eleifend ac augue. Vivamus euismod non augue euismod volutpat. Ut eget neque nec velit sagittis tempus.</p>

<p>Quisque a erat et ipsum eleifend ornare. Aliquam sit amet egestas elit. Ut felis tortor, tristique id fringilla quis, sollicitudin hendrerit elit. Sed pretium condimentum porta. Suspendisse hendrerit maximus ante in porttitor. Cras turpis massa, volutpat ut orci non, condimentum eleifend nibh. Nam vestibulum lacus iaculis, convallis dui ac, laoreet nunc. Nunc tincidunt risus et vestibulum ultricies.</p>

Core2Walkthrough/Pages/Activity.cshtml
@page
@model Core2Walkthrough.Pages.ActivityModel
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Activity";
}

<h2>Activity</h2>
<h3><font color="lime"> @Model.Message</font></h3>

@* Quick check to see which part of the code is being rendered.*@
@if (HttpContextAccessor.HttpContext.Session.GetString("name") == null)
{
    <h3>No Access</h3>
}
else
{
    <form method="post">
        <table class="table">
            <thead>
                <tr>
                    @*<th>ID </th>*@
                    <th>Title</th>
                    <th>XP</th>
                    <th>COOL_OFF_MINUTES</th>
                    <th>IS_ACTIVE</th>
                    <th>DATE_ENTERED</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var temp in Model.ActivityList)
                {
                    <tr>
                        @*<td>@temp.ID </td>*@
                        <td>@temp.Title</td>
                        <td>@temp.XP</td>
                        <td>@temp.COOL_OFF_MINUTES</td>
                        <td>@temp.IS_ACTIVE</td>
                        <td>@temp.DATE_ENTERED</td>
                        <td>
                            @if (temp.TIME_LEFT == 0)
                            {
                                //Matches up with the OnPostActivityDoAsync in the cs page.
                                <button type="submit" asp-page-handler="ActivityDo" asp-route-id="@temp.ID">Do</button>
                            }
                            else
                            {
                                //Utilizing some .NET ability here.
                                TimeSpan t = TimeSpan.FromSeconds((double)temp.TIME_LEFT);

                                <label>Left: mm: @Math.Floor(@t.TotalMinutes).ToString()   ss: @t.Seconds.ToString() </label>
                            }
                        </td>
                    </tr>
                }

            </tbody>

        </table>
    </form>
}

Core2Walkthrough/Pages/Admin.cshtml
@page
@model Core2Walkthrough.Pages.AdminModel
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor



@{
    ViewData["Title"] = "Admin";
}

<h2>Admin</h2>

<h3><font color="lime"> @Model.Message</font></h3>

@* Quick check to see which part of the code is being rendered.*@
@if (HttpContextAccessor.HttpContext.Session.GetString("name") == null && HttpContextAccessor.HttpContext.Session.GetString("is_admin") == null)
{
    <h3>No Access</h3>
}
else
{
    <h3>News</h3>
    <form method="post">
        <table class="table">
            <thead>
                <tr>
                    @*<th>id</th>*@
                    <th>Name</th>
                    <th>Date Added</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var temp in Model.NewsList)
                {
                    <tr>
                        @*<td>@temp.ID </td>*@
                        <td>@temp.TEXT</td>
                        <td>@temp.DATE_ENTERED</td>
                        <td>
                            @*Important information here.. matching up the 'asp-page-handler' to the CS function, and the asp-rout- variable name and value.*@
                            <button type="submit" asp-page-handler="DeleteNews" asp-route-id="@temp.ID">Delete</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>

    <h4>Add News</h4>
    <form method="post">
        @*<div asp-validation-summary="All"></div>*@
        <div>
            <label asp-for="NewsAdd.TEXT"></label>
            <input asp-for="NewsAdd.TEXT" />
        </div>
        <input asp-page-handler="NewsAdd" type="submit" value="Add News" />
    </form>
    <br /><br />

    <h3>Users</h3>
    <form method="post">
        <table class="table">
            <thead>
                <tr>
                    @*<th>id</th>*@
                    <th>Name</th>
                    <th>Date Entered</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var temp in Model.UserList)
                {
                    <tr>
                        @*<td>@temp.ID </td>*@
                        <td>@temp.Name</td>
                        <td>@temp.DATE_ENTERED</td>
                        <td>
                            @if (HttpContextAccessor.HttpContext.Session.GetString("id") != temp.ID.ToString())
                            {
                                <button type="submit" asp-page-handler="DeleteUser" asp-route-id="@temp.ID">Delete</button>
                            }
                            else
                            {
                                @Html.Raw("&nbsp;");
                            }
                        </td>
                    </tr>
                }

            </tbody>

        </table>
    </form>

    <br /><br />

    <h3>Activities</h3>
    <form method="post">
        <table class="table">
            <thead>
                <tr>
                    @*<th>ID </th>*@
                    <th>Title</th>
                    <th>XP</th>
                    <th>COOL_OFF_MINUTES</th>
                    <th>IS_ACTIVE</th>
                    <th>DATE_ENTERED</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var temp in Model.ActivityList)
                {
                    <tr>
                        @*<td>@temp.ID </td>*@
                        <td>@temp.Title</td>
                        <td>@temp.XP</td>
                        <td>@temp.COOL_OFF_MINUTES</td>
                        <td>@temp.IS_ACTIVE</td>
                        <td>@temp.DATE_ENTERED</td>
                        <td>
                            <button type="submit" asp-page-handler="ActivityDisable" asp-route-id="@temp.ID">Enable/Disable</button>
                        </td>
                    </tr>
                }

            </tbody>

        </table>
    </form>

    <h4>Add Activity</h4>
    <form method="post">
        <div>
            <label asp-for="ActivityAdd.Title"></label>
            <input asp-for="ActivityAdd.Title" />

            <label asp-for="ActivityAdd.Description"></label>
            <input asp-for="ActivityAdd.Description" />

            <label asp-for="ActivityAdd.XP"></label>
            <input asp-for="ActivityAdd.XP" />

            <label asp-for="ActivityAdd.COOL_OFF_MINUTES"></label>
            <input asp-for="ActivityAdd.COOL_OFF_MINUTES" />

            <label asp-for="ActivityAdd.IS_ACTIVE"></label>
            <input asp-for="ActivityAdd.IS_ACTIVE" />
        </div>
        <input asp-page-handler="ActivityAdd" type="submit" value="Add Activity" />
    </form>
}

Core2Walkthrough/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<h3>@Model.Message</h3>

<h1>Welcome!</h1>
<div>
    This is just the landing page for anyone visiting the site.  It can be filled with static text, formatted with CSS, or show data pulled from a database.
</div>
<br />
<div>
    <h3>News</h3>
    <div style="margin-left:20px;">
        @foreach (var temp in Model.NewsList)
        {
            <h4>@temp.DATE_ENTERED.ToShortDateString()</h4>
            <span style="margin-left:20px;">@temp.TEXT</span>
            <br />
        }
    </div>

</div>
<hr />
<a asp-page="Test">Test Page</a><br />
<a asp-page="TestUpload">Testing Upload</a>

Core2Walkthrough/Pages/Login.cshtml
@page
@model Core2Walkthrough.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
}

<h2>Login</h2>

<form method="post">

    <h3>@Model.Message</h3>


    @*<div asp-validation-summary="All"></div>*@
    <div>Name: <input asp-for="UserData.Name" value="test" /></div>
    <input type="submit" />
</form>

Core2Walkthrough/Pages/Test.cshtml
@page
@model Core2Walkthrough.Pages.TestModel
@{
    ViewData["Title"] = "Test";
}
<script src="~/js/jquery-3.3.1.min.js" type="text/javascript"></script>

<script type="text/javascript">
    //$(document).ready(function () {
    //    console.log("ready!");
    //});

    $(function () {
        $('#testDDSelectedAJAX').change(function () {
            //var end = this.value;
            //var firstDropVal = $('#pick').val();
            console.log("here!");
            var here = $('#testDDSelectedAJAX option:selected').text();
            console.log(here);

            $.ajax({
                type: 'GET',
                url: '/Test?handler=List',
                data: {
                    derp: here
                }, // null, // optional data
                dataType: 'text',
                headers:
                {
                    //required for Razor to verify not XSS
                    "RequestVerificationToken": $('input:hidden[name="__RequestVerificationToken"]').val()
                },
                success: function (result) {
                    // do something with result
                    console.log(result);
                    $("#coke").after().html('<lable>Success: ' + result + '</lable>');
                },
                error: function (req, status, error) {
                    // do something with error
                    console.log("error");
                    console.log(req);
                    console.log(status);
                    console.log(error);

                }

            });
        });


    });
</script>


<h2>Testing bits of functionality</h2>
<br />
<h3><font color="lime"> @Model.Message</font></h3>
<hr />
<h3>Dropdown lists</h3>
<form method="post">
    @* templated helper *@
    @* 1st param - the selected value to return on post, 2nd param the list from the model, 3rd parameter - some initial filler text *@
    @Html.DropDownListFor(a => a.testDDSelected, Model.testDD, "--Select a Value--")
    <button type="submit" asp-page-handler="DropDownList">Test</button>
</form>

<hr />
<h3>RadioButton</h3>
<form method="post">
    @Html.RadioButtonFor(a => a.testRadioButtonSelected, "A")@Html.Label("A")
    @Html.RadioButtonFor(a => a.testRadioButtonSelected, "B")@Html.Label("B")
    <button type="submit" asp-page-handler="RadioButton">Test</button>
</form>

<hr />
<h3>CheckBox</h3>
<form method="post">
    @Html.CheckBoxFor(a => a.isChecked)@Html.LabelFor(a => a.isChecked)
    <button type="submit" asp-page-handler="CheckBox">Test</button>
</form>

<hr />
<h3>Dropdown list with AJAX call to function</h3>
<div id="coke"></div>

<form method="post">
    @* templated helper *@
    @* 1st param - the selected value to return on post, 2nd param the list from the model, 3rd parameter - some initial filler text *@
    @Html.DropDownListFor(a => a.testDDSelectedAJAX, Model.testDDAJAX, "--Select a Value--", new { @id = "testDDSelectedAJAX" })
 </form>